export const FETCH_BOILER_TYPE = 'FETCH_BOILER_TYPE';
export const FETCH_BOILERTYPE_REQUEST = 'FETCH_BOILERTYPE_REQUEST';
export const ADD_BOILER_TYPE = 'ADD_BOILER_TYPE';
export const DELETE_BOILER_TYPE = 'DELETE_BOILER_TYPE';
export const UPDATE_BOILER_TYPE = 'UPDATE_BOILER_TYPE';
