export const GET_BOILERTYPES_FETCHING = 'GET_BOILERTYPES_FETCHING';
export const GET_BOILERTYPES_FULFILLED = 'GET_BOILERTYPES_FULFILLED';
export const GET_BOILERTYPES_REJECTED = 'GET_BOILERTYPES_REJECTED';

export const ADD_BOILERTYPE_FETCHING = 'ADD_BOILERTYPE_FETCHING';
export const ADD_BOILERTYPE_FULFILLED = 'ADD_BOILERTYPE_FULLFILLED';
export const ADD_BOILERTYPE_REJECTED = 'ADD_BOILERTYPE_REJECTED';

export const DELETE_BOILERTYPE_FETCHING = 'DELETE_BOILERTYPE_FETCHING';
export const DELETE_BOILERTYPE_FULFILLED = 'DELETE_BOILERTYPE_FULLFILLED';
export const DELETE_BOILERTYPE_REJECTED = 'DELETE_BOILERTYPE_REJECTED';

export const UPDATE_BOILERTYPE_FETCHING = 'UPDATE_BOILERTYPE_FETCHING';
export const UPDATE_BOILERTYPE_FULFILLED = 'UPDATE_BOILERTYPE_FULLFILLED';
export const UPDATE_BOILERTYPE_REJECTED = 'UPDATE_BOILERTYPE_REJECTED';
