export const GET_BOILERS_FETCHING = 'GET_BOILERS_FETCHING';
export const GET_BOILERS_FULFILLED = 'GET_BOILERS_FULFILLED';
export const GET_BOILERS_REJECTED = 'GET_BOILERS_REJECTED';

export const ADD_BOILER_FETCHING = 'ADD_BOILER_FETCHING';
export const ADD_BOILER_FULFILLED = 'ADD_BOILER_FULLFILLED';
export const ADD_BOILER_REJECTED = 'ADD_BOILER_REJECTED';

export const DELETE_BOILER_FETCHING = 'DELETE_BOILER_FETCHING';
export const DELETE_BOILER_FULFILLED = 'DELETE_BOILER_FULLFILLED';
export const DELETE_BOILER_REJECTED = 'DELETE_BOILER_REJECTED';

export const UPDATE_BOILER_FETCHING = 'UPDATE_BOILER_FETCHING';
export const UPDATE_BOILER_FULFILLED = 'UPDATE_BOILER_FULLFILLED';
export const UPDATE_BOILER_REJECTED = 'UPDATE_BOILER_REJECTED';
