export const LOGIN_FETCHING = 'LOGIN_FETCHIN';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';
export const SET_AUTHENTICATION = 'SET_AUTHENTICATION';
export const LOGOUT_FETCHING = 'LOGOUT_FETCHING';
export const LOGOUT_FULFILLED = 'LOGOUT_FULFILLED';
export const LOGOUT_REJECTED = 'LOGOUT_REJECTED';
