export const GET_TECHNICIANS_FETCHING = 'GET_TECHNICIANS_FETCHING';
export const GET_TECHNICIANS_FULFILLED = 'GET_TECHNICIANS_FULFILLED';
export const GET_TECHNICIANS_REJECTED = 'GET_TECHNICIANS_REJECTED';

export const ADD_TECHNICIAN_FETCHING = 'ADD_TECHNICIAN_FETCHING';
export const ADD_TECHNICIAN_FULFILLED = 'ADD_TECHNICIAN_FULLFILLED';
export const ADD_TECHNICIAN_REJECTED = 'ADD_TECHNICIAN_REJECTED';

export const DELETE_TECHNICIAN_FETCHING = 'DELETE_TECHNICIAN_FETCHING';
export const DELETE_TECHNICIAN_FULFILLED = 'DELETE_TECHNICIAN_FULLFILLED';
export const DELETE_TECHNICIAN_REJECTED = 'DELETE_TECHNICIAN_REJECTED';

export const UPDATE_TECHNICIAN_FETCHING = 'UPDATE_TECHNICIAN_FETCHING';
export const UPDATE_TECHNICIAN_FULFILLED = 'UPDATE_TECHNICIAN_FULLFILLED';
export const UPDATE_TECHNICIAN_REJECTED = 'UPDATE_TECHNICIAN_REJECTED';
